name: OTF
channels:
  - conda-forge
dependencies:
  - jupyter 
  - pip >= 24.0
  - python = 3.12
  - pip:
      - numpy
      - pandas
      - matplotlib
      - seaborn
      - scikit-learn
      - scipy
      - statsmodels
      - yfinance
      - quandl
      - pyfolio 
      - arch
      - statsmodels
      - yfinance
      - quandl
      - pyfolio
      - backtrader
      - backtrader2
      - stable-baselines3
      - gym
      - tensorboard
      - tensorflow